import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const prod = process.argv[2] === "production";
const nodeBuiltins = [
  ...builtinModules,
  ...builtinModules.map((name) => "node:" + name),
];

const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/commands",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    ...nodeBuiltins,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  banner: {
    js: "/* Generated by esbuild. Source: https://github.com/Ni-zav/latextifier-obsidian */",
  },
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
